### ISSUE TITLE
Support for Google Inbox

### ISSUE THREAD

**Issue by joshuaoliver** [peterhartree/inbox-when-ready#1]
Replicating the same functionality over to http://inbox.google.com

**Comment by peterhartree** [comment]
Thanks for the request @joshuaoliver. I've just added this feature for you. The update should roll out via the Chrome Web Store within the next 24 hours or so.

Hope this helps - I'd love to hear from you again if you've any other feedback or suggestions.

**Comment by joshuaoliver** [comment]
Amazing, looking forward to checking it out, I've upgraded to: 1.1.2
https://www.dropbox.com/s/2svy0xqywq0x75i/Screenshot%202015-11-02%2010.01.23.png?dl=0
however
no sure where the button should show up in google inbox, can't seem to see
it. I can find it via web inspector, but the CSS is displaying it under
some other stuff.

Thanks for doing this!

On Mon, Nov 2, 2015 at 7:06 AM Peter Hartree <notifications@github.com>
wrote:

> Thanks for the request @joshuaoliver <https://github.com/joshuaoliver>.
> I've just added this feature for you. The update should roll out via the
> Chrome Web Store within the next 24 hours or so.
>
> Hope this helps - I'd love to hear from you again if you've any other
> feedback or suggestions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterhartree/inbox-when-ready/issues/1#issuecomment-152859505>
> .
>
-- 
Joshua Oliver

**Comment by peterhartree** [comment]
Hmm.... I'll look into this within the next 48 hours and post back. Thanks for your patience, and sorry for the hassle @joshuaoliver.

**Comment by peterhartree** [comment]
@joshuaoliver: I've pushed an update to the Chrome Web Store. It should be with you within the next 24 hours or so.
