### ISSUE TITLE
Multiple buttons appearing

### ISSUE THREAD

**Issue by nuaniall** [peterhartree/inbox-when-ready#6]
Hi,
Sometimes when I refresh the 'hide' button appears multiple times across the top of the screen and fills the entire width.  It's like it's on an infinite loop and would just keep duplicating if it could.

Doesn't happen all the time so generally if I refresh it's fine. 

Still love it though!!

**Comment by nuaniall** [comment]
Update...

The multiple tabs seems to appear when I open a second gmail account. Pic attached

![image](https://cloud.githubusercontent.com/assets/18047975/14149127/91ea4854-f69a-11e5-93b4-edea0f7bb2d8.png)

**Comment by peterhartree** [comment]
Nice... this has enabled me to reproduce the issue! I'll push a fix this weekend and let you know :)

**Comment by nuaniall** [comment]
Perfect!

-Niall

**Comment by peterhartree** [comment]
@nuaniall I've just pushed a fix for this. Version 1.1.6 will be available on the Chrome Web Store within the next 60 minutes or so and your web browser should automatically update within 24 hours. If you don't want to wait, you can force Chrome to update immediately by following these instructions:

http://lifehacker.com/5805239/how-to-manually-update-your-chrome-extensions

Thanks again for reporting this issue and helping me to resolve it. Happy weekend!
